# Generated by Django 5.0.1 on 2024-01-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capstoneapp',
            name='id',
        ),
        migrations.AlterField(
            model_name='capstoneapp',
            name='index',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
